# Generated by Django 4.2 on 2023-04-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_followers', models.IntegerField(max_length=50)),
                ('instagram_following', models.IntegerField(max_length=50)),
                ('instagram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taskapp.instagramcredentials')),
            ],
        ),
    ]
