# Generated by Django 4.2 on 2023-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_instagramdatas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcredentials',
            name='instagram_username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramdatas',
            name='instagram_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramdatas',
            name='instagram_following',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
